apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiU2doaWVyIiwicGFzc3dvcmQiOiJnaHBfa2ZZbThQSUNwNVZiQUJkeDE0N3hISERRSzhpWHF2M21YNnlaIiwiYXV0aCI6IlUyZG9hV1Z5T21kb2NGOXJabGx0T0ZCSlEzQTFWbUpCUW1SNE1UUTNlRWhJUkZGTE9HbFljWFl6YlZnMmVWbz0ifX19
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
